model:
  meta_architecture: "DRCNN"
  drcnn:
    yolact_on: False
    yolact_tracking_on: True
    pretrained_yolact_tracking: "models/yolact_tracking/kitti/resnet50b10_600x300_gray/model_epoch_000039.pth"
    ssim_coefs: [ 0.18742550637410094 ]
    ssim_intercepts: [ 4.41360665450609 ]
    ssim_stds: [ 23.81503735 ]
    mask_mode: 'poly' # for evaltime, use mask, for save predictions, use poly
    idispnet_on: True
    detector_3d_on: True
    detector_3d:
      shuffle_points: False
      combine_2d3d: True
  yolact:
    num_classes: 2
    class_names: [ 'car' ]
    pretrained_backbone: ""
  yolact_tracking:
    pretrained_yolact: "models/yolact/kitti/resnet50_600x300_gray/model_iteration_117500.pth"
    alpha: 0.1
    beta: 10.0
    thresh: 0.0
  idispnet:
    pretrained_model: "models/idispnet/kitti_resizegray_112/bestmodel.pth"
    mindisp: -24
    maxdisp: 24
    input_size: 112
  pointpillars:
    num_point_features: 4
    pretrained_model: "models/pointpillars/disprcnn_112/train/model_epoch_000040.pth"
trt:
  onnx_path: "tmp"
  convert_to_trt:
    output_path: "tmp"
datasets:
  train: ("kittitrackingstereo_demo",)
  test: "kittitrackingstereo_demo"
solver:
  trainer: drcnn
  batch_size: 1
  max_lr: 0.001
  num_epochs: 1500
  optimizer: SGD
  scheduler: WarmupMultiStepLR
  warmup_iters: 500
  steps: [ 280000, 600000, 700000, 750000 ]
  bias_lr_factor: 1
  weight_decay: 0.0005
  weight_decay_bias: 0.0005
  save_every: True
  save_mode: epoch
  save_freq: 1
  dist:
    sampler:
      shuffle: True
input:
  shuffle: True
  transforms:
    - name: ConvertFromInts
    - name: Resize
      max_size: [ 600, 300 ]
      preserve_aspect_ratio: False
      discard_box_width: 0.007272727272727273
      discard_box_height: 0.007272727272727273
      resize_gt: False
    - name: BackboneTransform
      normalize: True
      mean: [ 103.94, 116.78, 123.68 ]
      std: [ 57.38, 57.12, 58.40 ]
      subtract_means: False
      to_float: False
      in_channel_order: 'BGR'
      channel_order: 'RGB'
dataset:
  kitti_tracking_stereo:
    use_gray: True
test:
  do_visualization: False
  evaluators: [ ]
  batch_size: 1
  save_predictions: False
#  force_recompute: False

dataloader:
  collator: ExtendedBatchCollator
  num_workers: 4