model:
  meta_architecture: "DRCNN"
  drcnn:
    yolact_on: False
    yolact_tracking_on: True
    pretrained_yolact_tracking: "models/yolact_tracking/kitti/resnet50b10resizegray_ped_from_coco/model_epoch_000119.pth"
    ssim_coefs: [ 0.27261221916974204 ]
    ssim_intercepts: [ 1.707562061026895 ]
    ssim_stds: [ 8.95778275 ]
    mask_mode: 'poly' # for evaltime, use mask, for save predictions, use poly
    idispnet_on: True
    detector_3d_on: True
    detector_3d:
      feature_map_size: [ 1, 248, 296 ]
      shuffle_points: False
      combine_2d3d: True
  yolact:
    num_classes: 2
    class_names: [ 'pedestrian' ]
    pretrained_backbone: ""
  yolact_tracking:
    pretrained_yolact: "models/yolact/kitti/resnet50resizegray_ped_from_coco/model_iteration_120000.pth"
    alpha: 0.1
    beta: 5.0
    thresh: 0.0
  idispnet:
    pretrained_model: "models/idispnet/kitti_resizegrayped_112/bestmodel.pth"
    mindisp: -24
    maxdisp: 24
    input_size: 112
  pointpillars:
    num_point_features: 4
    pretrained_model: "models/pointpillars/disprcnn_ped_112/train/model_epoch_000030.pth"
    vis_threshold: 0.5
    rpn:
      layer_strides: [ 1, 2, 2 ]
    post_center_limit_range: [ 0, -19.84, -2.5, 47.36, 19.84, 0.5 ]
    target_assigner:
      anchor_generators:
        sizes: [ 0.6, 0.8, 1.73 ] # wlh
        strides: [ 0.16, 0.16, 0.0 ]
        offsets: [ 0.08, -19.76, -1.465 ]
        rotations: [ 0, 1.57 ] # 0, pi/2
        matched_threshold: 0.5
        unmatched_threshold: 0.35
voxel_generator:
  point_cloud_range: [ 0, -19.84, -2.5, 47.36, 19.84, 0.5 ]
  voxel_size: [ 0.16, 0.16, 3 ]
datasets:
  train: ("kittitrackingstereo_train",)
  test: "kittitrackingstereo_valped"
  # test: "kittiobj_val"
  # test: "kittiobj_valmini"
solver:
  trainer: drcnn
  batch_size: 1
  max_lr: 0.001
  num_epochs: 1500
  optimizer: SGD
  scheduler: WarmupMultiStepLR
  warmup_iters: 500
  steps: [ 280000, 600000, 700000, 750000 ]
  bias_lr_factor: 1
  weight_decay: 0.0005
  weight_decay_bias: 0.0005
  save_every: True
  save_mode: epoch
  save_freq: 1
  dist:
    sampler:
      shuffle: True
input:
  shuffle: True
  transforms:
    - name: ConvertFromInts
    - name: Resize
      max_size: 546
      preserve_aspect_ratio: True
      discard_box_width: 0.007272727272727273
      discard_box_height: 0.007272727272727273
      resize_gt: False
    - name: BackboneTransform
      normalize: True
      mean: [ 103.94, 116.78, 123.68 ]
      std: [ 57.38, 57.12, 58.40 ]
      subtract_means: False
      to_float: False
      in_channel_order: 'BGR'
      channel_order: 'RGB'
dataset:
  kitti_tracking_stereo:
    use_gray: True
test:
  do_visualization: False
  evaluators: [ ]
  batch_size: 1
  save_predictions: False
#  force_recompute: False

dataloader:
  collator: ExtendedBatchCollator
  num_workers: 4