model:
  pointpillars:
    preprocess:
      save_dir: "data/disprcnn/kitti_second"
      velodyne_template: 'data/disprcnn/pseudo_lidar/%s/velodyne/%06d.bin'
      velodyne_reduced_dir: "data/disprcnn/kitti_second/training/velodyne_reduced/"