model:
  idispnet:
    preprocess:
      output_dir: 'data/vob_roi_ra_gray'
      prediction_template: 'models/drcnn/kitti_object/resnet50resizegray/inference/kittiobj_%s/predictions.pth'
datasets:
  train: ("kittiobj_train",)
  #  test: "kittiobj_train"
  test: "kittiobj_val"
dataset:
  kitti_object:
    filter_empty: False
    use_gray: True